# Generated by Django 4.2.3 on 2023-07-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='excerpt',
        ),
    ]
