# Generated by Django 4.2.3 on 2023-07-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_article_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='key_words',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
