# Generated by Django 4.2.3 on 2023-07-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_excerpt_alter_category_key_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='excerpt',
        ),
    ]
