# Generated by Django 4.2.3 on 2023-07-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_category_article_excerpt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
